# Generated by Django 3.2.8 on 2021-11-03 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import siteApp.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=20)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('dead', models.BooleanField(default=False)),
                ('kids', siteApp.custom_fields.ListField(blank=True, null=True)),
                ('site_created', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=200, unique=True)),
                ('delay', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('karma', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
                ('submitted', siteApp.custom_fields.ListField(blank=True, null=True)),
                ('site_created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siteApp.basemodel')),
                ('text', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('title', models.CharField(max_length=200)),
            ],
            bases=('siteApp.basemodel',),
        ),
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siteApp.basemodel')),
                ('descendants', models.IntegerField(blank=True, default=0)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('parts', siteApp.custom_fields.ListField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            bases=('siteApp.basemodel',),
        ),
        migrations.CreateModel(
            name='StoryModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siteApp.basemodel')),
                ('descendants', models.IntegerField(default=0)),
                ('url', models.URLField(null=True)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(max_length=200)),
            ],
            bases=('siteApp.basemodel',),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteApp.usermodel'),
        ),
        migrations.CreateModel(
            name='PollOptionModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siteApp.basemodel')),
                ('score', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteApp.pollmodel')),
            ],
            bases=('siteApp.basemodel',),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siteApp.basemodel')),
                ('text', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_parent', to='siteApp.basemodel')),
            ],
            bases=('siteApp.basemodel',),
        ),
    ]
